services:
  cryptodns:
    ports:
      - 127.0.0.1:4453:4453
      - 127.0.0.1:853:853
  letsencrypt:
    environment:
      - LETS_ENCRYPT_CUSTOM_FLAGS=--test-cert
      #- LETS_ENCRYPT_CUSTOM_FLAGS=--test-cert --dry-run
    #volumes:
    #  - ./letsencrypt/dns_credentials:/usr/local/letsencrypt/etc/dns_credentials:ro
  test:
    build:
      context: ./cryptodns
      dockerfile: Dockerfile.test
    depends_on:
      - cryptodns
    environment:
      - LETS_ENCRYPT_DOMAIN=${LETS_ENCRYPT_DOMAINS}
      - DNS_PROVIDER=${DNS_PROVIDER}
      - LETS_ENCRYPT_MAIL=${LETS_ENCRYPT_MAIL}
    volumes:
      - ./cryptodns/bin:/usr/local/bin
