services:
  cryptodns:
    build: cryptodns
    user: ${PUID}:${GUID}
    depends_on:
      - recursor
      - letsencrypt
    restart: "always"
    volumes:
      - ./cryptodns/conf:/etc/dnsdist:ro
      - ./.le/etc/live:/certs/live:ro
      - ./.le/etc/archive:/certs/archive:ro
  recursor:
    build: recursor
    restart: "always"
    volumes:
      - ./recursor/conf/filterlist.lua:/etc/powerdns/recursor.d/filterlist.lua:ro
  letsencrypt:
    build: letsencrypt
    user: ${PUID}:${GUID}
    volumes:
      - ./letsencrypt/dns_credentials:/etc/letsencrypt/dns_credentials:ro
      - ./.le/etc:/etc/letsencrypt
      - ./.le/lib:/var/lib/letsencrypt
      - ./.le/logs:/var/log/letsencrypt
    environment:
      - DNS_PROVIDER=${DNS_PROVIDER}
      - LETS_ENCRYPT_MAIL=${LETS_ENCRYPT_MAIL}
      - LETS_ENCRYPT_DOMAIN=${LETS_ENCRYPT_DOMAINS}
    restart: "always"