recursor:
  daemon: false
  hint_file: /usr/share/dns/root.hints
  public_suffix_list_file: /usr/share/publicsuffix/public_suffix_list.dat
  qname_minimization: true
  security_poll_suffix: ""
  setuid: 1033
  socket_owner: 1033
  lua_dns_script: /etc/powerdns/recursor.d/filter.lua

logging:
  loglevel: 6

incoming:
  listen:
    - 0.0.0.0:5353

packetcache:
  disable: true

dnssec:
  validation: validate